volumes:
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
  fastapi:
    build:
      context: TuneCast
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./TuneCast:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      MONGO_URL: mongodb://admin:password@mongo
      MICRO_WEATHER_API_KEY: ${MICRO_WEATHER_API_KEY}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_USER_SERVICE_API_HOST: http://localhost:8000
